ribbon:
  ReadTimeout: 20000
  ConnectTimeout: 20000


spring:
  cloud:
    gateway:
      routes:
        - id: product-service
          uri: http://product-service:8081
          predicates:
            - Path=/products/**

        - id: order-service
          uri: http://order-service:8082
          predicates:
            - Path=/orders/**

        - id: user-service
          uri: http://user-service:8083
          predicates:
            - Path=/users/**

management:
  endpoints:
    web:
      exposure:
        include: '*'

server:
  port: 8765