spring.application.name=order-service
spring.kafka.bootstrap-servers=localhost:9092

product-service.url=http://localhost:8081/api/v1/products

spring.messages.basename=ValidationMessages
spring.messages.encoding=UTF-8
spring.messages.fallback-to-system-locale=false

