spring.application.name=product-service-2
spring.kafka.bootstrap-servers=localhost:9092

order-service.url=http://localhost:8082/api/v1/orders

spring.messages.basename=ValidationMessages
spring.messages.encoding=UTF-8
spring.messages.fallback-to-system-locale=false
